[build.environment]
  NPM_CONFIG_REGISTRY = "https://registry.npmjs.org/"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium", "puppeteer-core", "puppeteer-extra", "puppeteer-extra-plugin-stealth"]
